- name: Download AWS CLI
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
  tags:
    - aws

- name: Unzip AWS CLI
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes
  tags:
    - aws

- name: Install AWS CLI
  become: true
  ansible.builtin.command:
    cmd: /tmp/aws/install --update
  tags:
    - aws

- name: Cleanup download
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/awscliv2.zip
    - /tmp/aws
  tags:
    - aws
