- name: Debian/Ubuntu Family | Add gpg signing key for Google Chrome
  become: true
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present
  tags:
    - install
    - chrome
- name: Debian/Ubuntu Family | Adding repository for Google Chrome
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: "google-chrome"
    update_cache: yes
  tags:
    - install
    - chrome
- name: Debian/Ubuntu Family | Installing Google Chrome
  become: true
  apt:
    name: "google-chrome-stable"
    state: present
    force_apt_get: yes
    update_cache: yes
  tags:
    - install
    - chrome
