- name: Download discord
  get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb
  tags:
    - install
    - discord


- name: Install discord .deb package
  become: true
  apt:
    deb: /tmp/discord.deb
  tags:
    - install
    - discord
