- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "me@alexgirard.ca"
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Alex Girard"
- name: Git personal setup name
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
