- name: Download Nvim
  become: true
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    dest: ~/nvim.appimage
  tags:
    - install
    - neovim

- name: Install Astrovim
  ansible.builtin.git:
    repo: 'https://github.com/AstroNvim/AstroNvim'
    dest: "~/.config/nvim"
    depth: 1
  tags: 
    - install 
    - neovim
